(() => {
  // ----- LIVE SOBRIETY COUNTER -----
  const soberSince = new Date('2025-04-17T00:52:48-04:00');
  const root = document.querySelector('#sobriety-live');
  if (root) {
    const units = ['years','months','days','hours','minutes','seconds'];
    const els = Object.fromEntries(units.map(u => [u, root.querySelector(`[data-unit="${u}"]`)]));
    const totalDaysEl = root.querySelector('[data-total-days]');
    const addYears=(d,n)=>{d=new Date(d);d.setFullYear(d.getFullYear()+n);return d};
    const addMonths=(d,n)=>{d=new Date(d);const day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);const max=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,max));return d};
    const addDays=(d,n)=>{d=new Date(d);d.setDate(d.getDate()+n);return d};
    function diff(start,end){let c=new Date(start),y=end.getFullYear()-c.getFullYear(),t=addYears(c,y);if(t>end){y--;t=addYears(c,y)}c=t;let m=(end.getFullYear()-c.getFullYear())*12+end.getMonth()-c.getMonth();t=addMonths(c,m);if(t>end){m--;t=addMonths(c,m)}c=t;let days=0;while(addDays(c,1)<=end&&days<32){c=addDays(c,1);days++}let ms=end-c,h=Math.floor(ms/3600000);ms-=h*3600000;let min=Math.floor(ms/60000);ms-=min*60000;let s=Math.floor(ms/1000);return{years:y,months:m,days,hours:h,minutes:min,seconds:s}}
    function tick(){const d=diff(soberSince,new Date());units.forEach(u=>{if(!els[u])return;els[u].querySelector('.sobriety-num').textContent=d[u];els[u].querySelector('.sobriety-label').textContent=`${u.slice(0,-1)}${d[u]===1?'':'s'}`});if(totalDaysEl)totalDaysEl.textContent=Math.floor((Date.now()-soberSince)/86400000).toLocaleString()}
    tick();setInterval(tick,1000);
  }

  // ----- MUSIC + STORY STYLES -----
  const css=document.createElement('style');
  css.textContent=`
  .story-song{margin:38px 0 8px;border:1px solid #ffffff20;border-radius:22px;background:#0c0c0c;overflow:hidden}.story-song-copy{padding:22px 24px}.story-song-copy small{display:block;color:#ff7487;font-size:11px;letter-spacing:.18em;font-weight:900;margin-bottom:8px}.story-song-copy h3{margin:0 0 10px;font-size:clamp(26px,4vw,42px);letter-spacing:-.04em}.story-song-copy p{margin:0!important;color:#aaa!important;font-size:16px!important}.story-song iframe{width:100%;aspect-ratio:16/9;border:0;background:#000;display:block}.story-song-links{display:flex;flex-wrap:wrap;gap:9px;padding:0 24px 22px}.story-song-links a{padding:10px 13px;border-radius:999px;border:1px solid #ffffff24;background:#151515;font-size:13px;font-weight:800}
  .music-why{padding:11vh 6vw;background:linear-gradient(180deg,#080808,#1a0a13 55%,#080808);border-top:1px solid #ffffff18;border-bottom:1px solid #ffffff18}.music-why .mw-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.75fr);gap:6vw;align-items:start}.music-why h2{font-size:clamp(54px,9vw,128px);line-height:.84;letter-spacing:-.065em;margin:0 0 35px}.music-why p{max-width:820px;color:#d0d0d0;line-height:1.75;font-size:clamp(17px,1.7vw,22px)}.mw-quote{border:1px solid #ffffff1f;border-radius:22px;background:#0d0d0d;padding:26px;position:sticky;top:110px}.mw-quote small{display:block;color:#ff7487;font-size:11px;letter-spacing:.18em;font-weight:900}.mw-quote strong{display:block;margin-top:14px;font-size:clamp(28px,4vw,54px);line-height:1}.mw-note{margin-top:20px;color:#888!important;font-size:14px!important}
  #crystal-music-button{position:fixed;right:18px;bottom:18px;z-index:9999;border:1px solid #ffffff33;background:#fff;color:#111;border-radius:999px;padding:14px 18px;font:800 14px/1 system-ui;box-shadow:0 12px 40px #0008;cursor:pointer}
  #crystal-music-modal{position:fixed;inset:0;z-index:10000;background:#050505f5;display:none;overflow:auto;-webkit-overflow-scrolling:touch;color:#fff;font-family:system-ui}#crystal-music-modal.open{display:block}.cm-wrap{max-width:920px;margin:auto;padding:28px 18px 60px}.cm-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:20px}.cm-head h2{margin:0;font-size:clamp(34px,7vw,72px);letter-spacing:-.05em}.cm-close{border:1px solid #ffffff33;background:#151515;color:#fff;width:48px;height:48px;border-radius:50%;font-size:24px;cursor:pointer}.cm-artist{margin:34px 0 12px;color:#ff7487;font-size:12px;font-weight:900;letter-spacing:.18em}.cm-track{border:1px solid #ffffff1f;background:#0d0d0d;border-radius:20px;padding:16px;margin:14px 0}.cm-track h3{margin:0 0 10px;font-size:22px}.cm-frame{aspect-ratio:16/9;width:100%;border:0;border-radius:14px;background:#000}.cm-links{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px}.cm-link{display:inline-flex;align-items:center;justify-content:center;padding:11px 14px;border-radius:999px;border:1px solid #ffffff26;background:#151515;color:#fff;text-decoration:none;font-weight:750}.cm-note{color:#999;line-height:1.6;font-size:13px;margin-top:16px}
  @media(max-width:780px){.music-why .mw-grid{grid-template-columns:1fr}.mw-quote{position:relative;top:auto}}@media(max-width:600px){#crystal-music-button{right:12px;bottom:12px;padding:13px 16px}.cm-wrap{padding-top:16px}.cm-head h2{font-size:40px}}
  `;
  document.head.appendChild(css);

  // ----- LEAN WIT ME INSIDE CRYSTAL'S STORY -----
  const recovery=document.querySelector('#my-story');
  if(recovery && !document.querySelector('#story-lean-wit-me')){
    const copy=recovery.querySelector('.recovery-copy');
    const card=document.createElement('div');
    card.id='story-lean-wit-me';card.className='story-song';
    card.innerHTML=`<div class="story-song-copy"><small>A SONG I PUT WITH MY STORY</small><h3>Juice WRLD — Lean Wit Me</h3><p>I put this here because it connects directly to the addiction side of my story. Sometimes a song can say the fear, dependence, denial, pain, and exhaustion around using more clearly than I can explain it myself.</p></div><iframe loading="lazy" src="https://www.youtube.com/embed/5SejM_hBvMM?playsinline=1&rel=0" title="Juice WRLD - Lean Wit Me" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><div class="story-song-links"><a target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=5SejM_hBvMM">YouTube</a><a target="_blank" rel="noopener" href="https://open.spotify.com/search/Juice%20WRLD%20Lean%20Wit%20Me">Spotify</a><a target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=Juice%20WRLD%20Lean%20Wit%20Me">Apple Music</a></div>`;
    if(copy) copy.appendChild(card);
  }

  // ----- WHY I ADDED MUSIC SECTION -----
  if(recovery && !document.querySelector('#why-music')){
    const section=document.createElement('section');section.id='why-music';section.className='music-why';
    section.innerHTML=`<div class="eyebrow">WHY I ADDED MUSIC</div><div class="mw-grid"><div><h2>WHEN WORDS<br>DON'T COME.</h2><p>I added music to this website because sometimes music speaks louder when we can't. Addiction, grief, cravings, guilt, fear, losing people, and trying to recover can be hard to explain in a normal sentence. Sometimes you know exactly what you feel, but you still cannot make the words come out.</p><p>A song can reach that place first. It can describe the chaos of addiction without turning it into a statistic. It can show the difference between how something looks from the outside and how it actually feels to the person living through it. It can make somebody feel understood before they are ready to talk.</p><p>The songs here are not meant to glorify drugs. I chose them because they talk about the reality around addiction: dependence, self-destruction, wanting to stop, being scared of what comes next, losing control, watching someone you love struggle, and trying to survive long enough to change.</p><p>For me, music has also been a way to remember people. Artists like Juice WRLD and Lil Peep were real people before they became overdose headlines. Their music can carry pieces of what they were feeling, and it reminds me that behind every addiction story is a person who had a voice, people who loved them, and a life bigger than the substance involved.</p><p>That is why the music belongs on this site. Facts can teach you what a drug does. Music can sometimes help you understand what addiction feels like.</p><p class="mw-note">— Crystal</p></div><aside class="mw-quote"><small>CRYSTAL · WHY MUSIC</small><strong>“Sometimes music speaks louder when we can't.”</strong></aside></div>`;
    recovery.insertAdjacentElement('afterend',section);
  }

  // ----- ALWAYS-VISIBLE MUSIC BUTTON + CROSS-PLATFORM MODAL -----
  if (document.querySelector('#crystal-music-button')) return;
  const btn=document.createElement('button');btn.id='crystal-music-button';btn.textContent='♫ MUSIC';btn.setAttribute('aria-label','Open recovery music player');
  const modal=document.createElement('div');modal.id='crystal-music-modal';modal.innerHTML=`<div class="cm-wrap"><div class="cm-head"><div><div style="color:#ff7487;font-size:11px;font-weight:900;letter-spacing:.18em">RECOVERY SOUNDTRACK</div><h2>MUSIC</h2></div><button class="cm-close" aria-label="Close">×</button></div>
  <div class="cm-artist">J. COLE</div>
  <div class="cm-track"><h3>Once an Addict (Interlude)</h3><iframe class="cm-frame" loading="lazy" src="https://www.youtube.com/embed/uirzHXHpgqM?playsinline=1&rel=0" title="J. Cole - Once an Addict (Interlude)" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><div class="cm-links"><a class="cm-link" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=uirzHXHpgqM">YouTube</a><a class="cm-link" target="_blank" rel="noopener" href="https://open.spotify.com/search/J.%20Cole%20Once%20an%20Addict">Spotify</a><a class="cm-link" target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=J.%20Cole%20Once%20an%20Addict">Apple Music</a></div></div>
  <div class="cm-track"><h3>FRIENDS (feat. kiLL edward)</h3><iframe class="cm-frame" loading="lazy" src="https://www.youtube.com/embed/4JmZ2PgzTos?playsinline=1&rel=0" title="J. Cole - FRIENDS" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><div class="cm-links"><a class="cm-link" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=J.+Cole+FRIENDS+kiLL+edward">YouTube</a><a class="cm-link" target="_blank" rel="noopener" href="https://open.spotify.com/search/J.%20Cole%20FRIENDS%20kiLL%20edward">Spotify</a><a class="cm-link" target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=J.%20Cole%20FRIENDS%20kiLL%20edward">Apple Music</a></div></div>
  <div class="cm-artist">JUICE WRLD</div>
  <div class="cm-track"><h3>Lean Wit Me</h3><iframe class="cm-frame" loading="lazy" src="https://www.youtube.com/embed/5SejM_hBvMM?playsinline=1&rel=0" title="Juice WRLD - Lean Wit Me" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><div class="cm-links"><a class="cm-link" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=5SejM_hBvMM">YouTube</a><a class="cm-link" target="_blank" rel="noopener" href="https://open.spotify.com/search/Juice%20WRLD%20Lean%20Wit%20Me">Spotify</a><a class="cm-link" target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=Juice%20WRLD%20Lean%20Wit%20Me">Apple Music</a></div></div>
  <div class="cm-track"><h3>Wishing Well</h3><iframe class="cm-frame" loading="lazy" src="https://www.youtube.com/embed/C5i-UnuUKUI?playsinline=1&rel=0" title="Juice WRLD - Wishing Well" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><div class="cm-links"><a class="cm-link" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=C5i-UnuUKUI">YouTube</a><a class="cm-link" target="_blank" rel="noopener" href="https://open.spotify.com/search/Juice%20WRLD%20Wishing%20Well">Spotify</a><a class="cm-link" target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=Juice%20WRLD%20Wishing%20Well">Apple Music</a></div></div>
  <div class="cm-artist">LIL PEEP</div>
  <div class="cm-track"><h3>Save That Shit</h3><iframe class="cm-frame" loading="lazy" src="https://www.youtube.com/embed/WvV5TbJc9tQ?playsinline=1&rel=0" title="Lil Peep - Save That Shit" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><div class="cm-links"><a class="cm-link" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=Lil+Peep+Save+That+Shit+official">YouTube</a><a class="cm-link" target="_blank" rel="noopener" href="https://open.spotify.com/search/Lil%20Peep%20Save%20That%20Shit">Spotify</a><a class="cm-link" target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=Lil%20Peep%20Save%20That%20Shit">Apple Music</a></div></div>
  <div class="cm-track"><h3>Awful Things</h3><iframe class="cm-frame" loading="lazy" src="https://www.youtube.com/embed/zOujzvtwZ6M?playsinline=1&rel=0" title="Lil Peep - Awful Things" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><div class="cm-links"><a class="cm-link" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=Lil+Peep+Awful+Things+official">YouTube</a><a class="cm-link" target="_blank" rel="noopener" href="https://open.spotify.com/search/Lil%20Peep%20Awful%20Things">Spotify</a><a class="cm-link" target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=Lil%20Peep%20Awful%20Things">Apple Music</a></div></div>
  <div class="cm-note">Use the controls inside each video for play, pause, seeking, volume, fullscreen, and AirPlay/Picture-in-Picture where supported. Mobile browsers may require one tap before audio can start.</div></div>`;
  document.body.append(btn,modal);
  const close=()=>modal.classList.remove('open');btn.addEventListener('click',()=>modal.classList.add('open'));modal.querySelector('.cm-close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();